name: pangu-weather-att-head-vis
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - onnx
  - onnxruntime
  - tqdm
  - xarray
  - zarr
  - fsspec
  - gcsfs
  - ipykernel
  - jupyterlab
  - ipywidgets
  - plotly
  - jupyterlab-plotly-extension
